// src/lib/kayaks.ts
// WKF — Catálogo de kayaks.
// v1.010: sin cambios funcionales. Los dos kayaks del usuario
// (Dolphin Propel 12 y Fisher Pro 12) siguen apareciendo como
// entradas más del catálogo, sin ningún destacado. Norma de
// privacidad de datos personales.

import type { CategoriaKayak } from './verdict.ts';

export type Propulsion = 'pala' | 'pedal_aletas' | 'pedal_helice';
export type CategoriaDirectiva = 'A' | 'B' | 'C' | 'D' | 'no_certificado';
export type TipoCasco = 'V' | 'U' | 'plano';

export interface Kayak {
  id: string;
  marca: string;
  modelo: string;
  eslora: number;
  manga: number;
  volumen: number;
  tipoCasco: TipoCasco;
  autovaciable: boolean;
  timon: boolean;
  compartimentosEstancos: boolean;
  capacidadCarga: number;
  propulsion: Propulsion;
  categoriaWKF: CategoriaKayak;
  categoriaDirectiva: CategoriaDirectiva;
  certificado: boolean;
  verificado: boolean;
}

export const CATALOGO_KAYAKS: Kayak[] = [
  {
    id: 'hobie-mirage-outback',
    marca: 'Hobie',
    modelo: 'Mirage Outback',
    eslora: 3.66,
    manga: 0.86,
    volumen: 350,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pedal_aletas',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'hobie-mirage-pro-angler-14',
    marca: 'Hobie',
    modelo: 'Mirage Pro Angler 14',
    eslora: 4.17,
    manga: 0.96,
    volumen: 450,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 250,
    propulsion: 'pedal_aletas',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'hobie-mirage-revolution-13',
    marca: 'Hobie',
    modelo: 'Mirage Revolution 13',
    eslora: 4.01,
    manga: 0.71,
    volumen: 300,
    tipoCasco: 'V',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 150,
    propulsion: 'pedal_aletas',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'native-slayer-propel-13',
    marca: 'Native Watercraft',
    modelo: 'Slayer Propel 13',
    eslora: 3.96,
    manga: 0.81,
    volumen: 380,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 200,
    propulsion: 'pedal_helice',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'native-titan-13-5',
    marca: 'Native Watercraft',
    modelo: 'Titan 13.5',
    eslora: 4.11,
    manga: 0.91,
    volumen: 420,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 250,
    propulsion: 'pedal_helice',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'wilderness-radar-135',
    marca: 'Wilderness Systems',
    modelo: 'Radar 135',
    eslora: 4.11,
    manga: 0.81,
    volumen: 400,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 200,
    propulsion: 'pedal_helice',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'wilderness-thresher-140',
    marca: 'Wilderness Systems',
    modelo: 'Thresher 140',
    eslora: 4.27,
    manga: 0.71,
    volumen: 350,
    tipoCasco: 'V',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pala',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'jackson-big-rig-hd',
    marca: 'Jackson Kayak',
    modelo: 'Big Rig HD',
    eslora: 3.96,
    manga: 0.91,
    volumen: 400,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 250,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'jackson-kraken-13-5',
    marca: 'Jackson Kayak',
    modelo: 'Kraken 13.5',
    eslora: 4.11,
    manga: 0.76,
    volumen: 350,
    tipoCasco: 'V',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 200,
    propulsion: 'pala',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'old-town-predator-pdl',
    marca: 'Old Town',
    modelo: 'Predator PDL',
    eslora: 4.11,
    manga: 0.86,
    volumen: 420,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 250,
    propulsion: 'pedal_helice',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'old-town-sportsman-120',
    marca: 'Old Town',
    modelo: 'Sportsman 120',
    eslora: 3.66,
    manga: 0.81,
    volumen: 350,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 200,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'ocean-kayak-trident-13',
    marca: 'Ocean Kayak',
    modelo: 'Trident 13',
    eslora: 3.96,
    manga: 0.71,
    volumen: 300,
    tipoCasco: 'V',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 150,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'ocean-kayak-prowler-13',
    marca: 'Ocean Kayak',
    modelo: 'Prowler 13',
    eslora: 3.96,
    manga: 0.71,
    volumen: 300,
    tipoCasco: 'V',
    autovaciable: true,
    timon: false,
    compartimentosEstancos: false,
    capacidadCarga: 150,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'perception-pescador-pro-12',
    marca: 'Perception',
    modelo: 'Pescador Pro 12',
    eslora: 3.66,
    manga: 0.81,
    volumen: 350,
    tipoCasco: 'U',
    autovaciable: true,
    timon: false,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'feelfree-lure-11-5',
    marca: 'FeelFree',
    modelo: 'Lure 11.5',
    eslora: 3.51,
    manga: 0.86,
    volumen: 350,
    tipoCasco: 'U',
    autovaciable: true,
    timon: false,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'riot-escape-12',
    marca: 'Riot Kayaks',
    modelo: 'Escape 12',
    eslora: 3.66,
    manga: 0.76,
    volumen: 300,
    tipoCasco: 'U',
    autovaciable: true,
    timon: false,
    compartimentosEstancos: false,
    capacidadCarga: 150,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'viking-profish-reload',
    marca: 'Viking Kayaks',
    modelo: 'Profish Reload',
    eslora: 4.27,
    manga: 0.76,
    volumen: 350,
    tipoCasco: 'V',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 200,
    propulsion: 'pala',
    categoriaWKF: 'K4',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'viking-profish-gt',
    marca: 'Viking Kayaks',
    modelo: 'Profish GT',
    eslora: 3.96,
    manga: 0.76,
    volumen: 300,
    tipoCasco: 'V',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 150,
    propulsion: 'pala',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: true,
    verificado: true,
  },
  {
    id: 'stealth-profisha-525',
    marca: 'Stealth Kayaks',
    modelo: 'Profisha 525',
    eslora: 5.25,
    manga: 0.66,
    volumen: 400,
    tipoCasco: 'V',
    autovaciable: false,
    timon: true,
    compartimentosEstancos: true,
    capacidadCarga: 200,
    propulsion: 'pala',
    categoriaWKF: 'K5',
    categoriaDirectiva: 'C',
    certificado: true,
    verificado: true,
  },
  {
    id: 'stealth-profisha-475',
    marca: 'Stealth Kayaks',
    modelo: 'Profisha 475',
    eslora: 4.75,
    manga: 0.66,
    volumen: 350,
    tipoCasco: 'V',
    autovaciable: false,
    timon: true,
    compartimentosEstancos: true,
    capacidadCarga: 180,
    propulsion: 'pala',
    categoriaWKF: 'K5',
    categoriaDirectiva: 'C',
    certificado: true,
    verificado: true,
  },
  {
    id: 'epic-v5',
    marca: 'Epic Kayaks',
    modelo: 'V5',
    eslora: 5.2,
    manga: 0.51,
    volumen: 300,
    tipoCasco: 'V',
    autovaciable: false,
    timon: true,
    compartimentosEstancos: true,
    capacidadCarga: 150,
    propulsion: 'pala',
    categoriaWKF: 'K5',
    categoriaDirectiva: 'C',
    certificado: true,
    verificado: true,
  },
  {
    id: 'epic-v6',
    marca: 'Epic Kayaks',
    modelo: 'V6',
    eslora: 6.1,
    manga: 0.51,
    volumen: 350,
    tipoCasco: 'V',
    autovaciable: false,
    timon: true,
    compartimentosEstancos: true,
    capacidadCarga: 180,
    propulsion: 'pala',
    categoriaWKF: 'K5',
    categoriaDirectiva: 'C',
    certificado: true,
    verificado: true,
  },
  {
    id: 'dolphin-propel-12',
    marca: 'Dolphin',
    modelo: 'Propel 12',
    eslora: 3.66,
    manga: 0.81,
    volumen: 350,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pedal_helice',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: false,
    verificado: false,
  },
  {
    id: 'fisher-pro-12-aletas',
    marca: 'Fisher',
    modelo: 'Pro 12',
    eslora: 3.66,
    manga: 0.8,
    volumen: 330,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pedal_aletas',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: false,
    verificado: false,
  },
  {
    id: 'fisher-pro-12-helice',
    marca: 'Fisher',
    modelo: 'Pro 12',
    eslora: 3.66,
    manga: 0.8,
    volumen: 330,
    tipoCasco: 'U',
    autovaciable: true,
    timon: true,
    compartimentosEstancos: false,
    capacidadCarga: 180,
    propulsion: 'pedal_helice',
    categoriaWKF: 'K3',
    categoriaDirectiva: 'D',
    certificado: false,
    verificado: false,
  },
];

export function buscarKayakPorId(id: string): Kayak | undefined {
  return CATALOGO_KAYAKS.find((k) => k.id === id);
}

export function buscarKayaksPorNombre(texto: string): Kayak[] {
  const q = texto.trim().toLowerCase();
  if (!q) return [];
  return CATALOGO_KAYAKS.filter((k) =>
    `${k.marca} ${k.modelo}`.toLowerCase().includes(q)
  );
}